### ISSUE TITLE
TLS encryption

### ISSUE THREAD

**Issue by alitvak69** [joshuaprunier/trite#14]
Executing dump command with trite causes this error message

TLS encryption requested but server does not support TLS

I am not sure what this error is due and how to fix it.

**Comment by joshuaprunier** [comment]
This is a  bug. I recently added TLS to all the MySQL databases where I work and modified trite to support that. The bug is it assumes TLS is configured when making the connection.

The fix should be fairly straightforward. I just need to figure out if I want to require the user to specify a tls flag or auto detect.

**Comment by joshuaprunier** [comment]
Commit 9635aa6d58a1b288241d498ac52666de29789841 fixes the TLS issue. Native auth is now the default and a new -tls flag can be specified in client and dump mode to send cleartext passwords & TLS parameters to the go MySQL driver when establishing a connection.

**Comment by alitvak69** [comment]
Thank you.  I will test it ASAP. Happy holidays.
